export const GET_ALL_ACCOUNTS = "GET_ALL_ACCOUNTS";
export const GET_ALL_SALES_PERSONS = "GET_ALL_SALES_PERSONS";
export const GET_RECENT_TRANSACTIONS = "GET_RECENT_TRANSACTIONS";
export const GET_ALL_TRANSACTIONS = "GET_ALL_TRANSACTIONS";
export const GET_ALL_AUDIT_LOGS = "GET_ALL_AUDIT_LOGS";

export const GET_ALL_OUTWARD = "GET_ALL_OUTWARD";
export const GET_ALL_SESSIONS = "GET_ALL_SESSIONS";
export const GET_ALL_USERS = "GET_ALL_USERS";
export const GET_STATS = "GET_STATS";
export const GET_MONTHLY_TRANS = "GET_MONTHLY_TRANS";
export const GET_SAVINGS_PERCENTAGE = "GET_SAVINGS_PERCENTAGE";



export const GET_ALL_ADMIN_USERS = "GET_ALL_ADMIN_USERS";
export const GET_ALL_ASSETS = "GET_ALL_ASSETS";
export const GET_ASSET_DETAILS = "GET_ASSET_DETAILS";

export const GET_ALL_RATES = "GET_ALL_RATES";

export const GET_CREDIT_ENTRY = "GET_CREDIT_ENTRY";
export const GET_EMPLOYEE_INFOS = "";


export const GET_ALL_ASSETS_CATEGORY = "GET_ALL_ASSETS_CATEGORY";
export const GET_CATEGORY_DETAILS = "GET_CATEGORY_DETAILS";
export const GET_ALL_SAVINGS = "GET_ALL_SAVINGS";





